name: staffapp
description: Staff App

version: 1.0.0+4

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^0.19.3
  shared_preferences: ^0.5.6
  flutter_launcher_icons: ^0.7.4
  firebase: ^8.0.0
  firebase_messaging: ^7.0.3
  firebase_crashlytics: ^0.1.3+3
  connectivity: ^0.4.8+6
  shimmer: ^1.1.2
  flutter_bloc: ^6.0.0
  flutter_slidable: ^0.5.7
  equatable: ^1.2.0
  dio: ^3.0.4
  rxdart: ^0.21.0
  qr_flutter: ^3.1.0
  jwt_decoder: ^1.0.4
  dotted_line: ^2.0.2
  dotted_border: ^1.0.7
  numberpicker: ^1.3.0
  web_socket_channel: ^1.2.0
  scrollable_positioned_list: ^0.1.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.0.0
  json_serializable: ^2.0.0

flutter_icons:
  android: true
  ios: true
  image_path: ""

flutter:
  uses-material-design: true

  assets:
    - images/

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins.ttf

    - family: Roboto
      fonts:
        - asset: fonts/Roboto.ttf
